/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicartagena.poo.ventanas;

/**
 *
 * @author zunig
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuRestaurante = new javax.swing.JMenu();
        itemnsAgregarRestaurante = new javax.swing.JMenuItem();
        menuMenu = new javax.swing.JMenu();
        itemnsAgregarMenus = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        ItemsAgregarCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..:GESTION DE RESTAURANTE");

        menuRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/poo/ventanas/Iconos/Restaurante24pixeles.png"))); // NOI18N
        menuRestaurante.setText("Restaurante");
        menuRestaurante.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        itemnsAgregarRestaurante.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        itemnsAgregarRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/poo/ventanas/Iconos/Agregar24pixeles.png"))); // NOI18N
        itemnsAgregarRestaurante.setText("Agregar Restaurante");
        itemnsAgregarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnsAgregarRestauranteActionPerformed(evt);
            }
        });
        menuRestaurante.add(itemnsAgregarRestaurante);

        barraMenu.add(menuRestaurante);

        menuMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/poo/ventanas/Iconos/Menu24pixeles.png"))); // NOI18N
        menuMenu.setText("Menú");
        menuMenu.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        itemnsAgregarMenus.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        itemnsAgregarMenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/poo/ventanas/Iconos/Agregar24pixeles.png"))); // NOI18N
        itemnsAgregarMenus.setText("Agregar menú");
        itemnsAgregarMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnsAgregarMenusActionPerformed(evt);
            }
        });
        menuMenu.add(itemnsAgregarMenus);

        barraMenu.add(menuMenu);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/poo/ventanas/Iconos/Cliente24pixeles.png"))); // NOI18N
        menuCliente.setText("Cliente");
        menuCliente.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        ItemsAgregarCliente.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        ItemsAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/poo/ventanas/Iconos/Agregar24pixeles.png"))); // NOI18N
        ItemsAgregarCliente.setText("Agregar cliente");
        ItemsAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsAgregarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(ItemsAgregarCliente);

        barraMenu.add(menuCliente);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemnsAgregarMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnsAgregarMenusActionPerformed
        // TODO add your handling code here:
         VentanaMenu ventanamenu = new VentanaMenu(this, true);
        ventanamenu.setLocationRelativeTo(this);
        ventanamenu.setVisible(true);
    }//GEN-LAST:event_itemnsAgregarMenusActionPerformed

    private void itemnsAgregarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnsAgregarRestauranteActionPerformed
           VentanaRestaurante ventanaRestaurante = new VentanaRestaurante(this, true);
        ventanaRestaurante.setLocationRelativeTo(this);
        ventanaRestaurante.setVisible(true);       
    
    }//GEN-LAST:event_itemnsAgregarRestauranteActionPerformed

    private void ItemsAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsAgregarClienteActionPerformed
        // TODO add your handling code here:
         VentanaCliente ventanacliente = new VentanaCliente(this, true);
         ventanacliente.setLocationRelativeTo(this);
         ventanacliente.setVisible(true);
    }//GEN-LAST:event_ItemsAgregarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemsAgregarCliente;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemnsAgregarMenus;
    private javax.swing.JMenuItem itemnsAgregarRestaurante;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenu menuRestaurante;
    // End of variables declaration//GEN-END:variables
}
